### ISSUE TITLE
Clean and minimal !

### ISSUE THREAD

**Issue by gb-jos** [yx208/elegant-theme#1]
Just found the theme, and have to say it looks very clean with the new JetBrains UI

<img width="3840" alt="Screenshot 2022-12-13 at 10 11 18 AM" src="https://user-images.githubusercontent.com/98774951/207275654-921919f5-c8f7-45b4-ad25-8df694144342.png">

There is just two things that keeps me from calling this the perfect theme for me. Wanted to mention to see what's your thoughts

- Would have loved to get rid of the vertical line between the line numbers and code, personally find it distracting
- The same above for the line between the code pane splits, would be super minimal and clean.
- The run configuration widget background when ide is not in focus, would be cool to have it match the toolbar colour
<img width="631" alt="Screenshot 2022-12-13 at 10 20 05 AM" src="https://user-images.githubusercontent.com/98774951/207277691-1c97c21e-2225-496b-bae5-75de8fa77653.png">

**Comment by leolin-idah** [comment]
Thank you for your valuable advice! If they are adopted later, I'll update them in the new version.

**Comment by leolin-idah** [comment]
For the first and second suggestions; I think the vertical line between the line number and code, let us know where the code starts.

For the third suggestion, I think this is a good idea, but I didn't find a solution in the Intellij related configuration. Although there are other means, but they affect other parts. If JetBrains's configuration is updated, I will add them. Thanks!

**Comment by ghost** [comment]
@yx208 Thanks for looking at this, makes perfect sense, 1 and 2 are just a bit strange personal preference anyways, i have a forked local version that achieves that and it works perfect. 

Sorry but just another question regarding the run widget, in run state, it has colors with bad contrast, would that be something that is configurable in a straightforward way 
<img width="530" alt="Screenshot 2022-12-19 at 9 48 49 AM" src="https://user-images.githubusercontent.com/52130524/208384970-ea096455-1dc7-4e78-9f55-09c45af4a6a5.png">

**Comment by leolin-idah** [comment]
> @yx208 Thanks for looking at this, makes perfect sense, 1 and 2 are just a bit strange personal preference anyways, i have a forked local version that achieves that and it works perfect.
> 
> Sorry but just another question regarding the run widget, in run state, it has colors with bad contrast, would that be something that is configurable in a straightforward way <img alt="Screenshot 2022-12-19 at 9 48 49 AM" width="530" src="https://user-images.githubusercontent.com/52130524/208384970-ea096455-1dc7-4e78-9f55-09c45af4a6a5.png">

In the IDE active state, the background of the Run Widget can be set, but in the window inactive state, JetBrains' does not provide the corresponding configuration.
