### ISSUE TITLE
Ability to change the background color of the theme

### ISSUE THREAD

**Issue by andriesfc** [yx208/elegant-theme#5]
I do like the font colors used, but I honestly dislike the greenish hue in the dark background. Is there anyway to change this? And in all fairness, I avoid any dark theme with either greenish or brownish tints.

**Comment by yx208** [comment]
Thank you for liking! During the early stages of creating this theme, I spent a long time deliberating over the choice of colors. Green, as one of the primary colors, plays a role in balancing the visual elements in the theme. The specific green hue I used has been adjusted continuously to be as comfortable as possible.

If this color is still an issue for you, you can clone the project and replace the colors as needed. I have listed all the colors used, and there are only two shades of green. If you are unsure which colors to use, you can refer to "https://www.zhongguose.com/". 😊

**Comment by leolin-idah** [comment]
> I do like the font colors used, but I honestly dislike the greenish hue in the dark background. Is there anyway to change this? And in all fairness, I avoid any dark theme with either greenish or brownish tints.

Thank you for liking! During the early stages of creating this theme, I spent a long time deliberating over the choice of colors. Green, as one of the primary colors, plays a role in balancing the visual elements in the theme. The specific green hue I used has been adjusted continuously to be as comfortable as possible.

If this color is still an issue for you, you can clone the project and replace the colors as needed. I have listed all the colors used, and there are only two shades of green. If you are unsure which colors to use, you can refer to "https://www.zhongguose.com/". 😊

**Comment by andriesfc** [comment]
Thanx for the info. Will checkout the project and play with it.
